### ISSUE TITLE
This week's checklist

### ISSUE THREAD

**Issue by Sophie-Le-Blanc** [Sophie-Le-Blanc/test#41]

**Comment by Sophie-Le-Blanc** [comment]
July 17 - July 21, 2017:
- [x] ask Juan to run SEPTA (both) and MCTA feeds for RT accuracy (for Swiftly)
- [x] ask Katie/Michelle and data team about Denver/Houston issues (for Swiftly)
- [x] follow up w/ SMART
- [x] email Ray
- [x] reply Lansing
- [x] reply to Jeff Parish
- [x] follow up with NY port authority
- [x] Canberra
- [x] ARTM call
- [x] call Jamison real estate
- [x] check ETA w/ Juan
- [x] call fido (bill)
- [x] fill in #s on spreadsheet (NPD + CUTA)
- [x] call SMART
- [x] start STM proposal bullet points
- [x] Rabbit Transit call
- [x] check RTD issues status

**Comment by Sophie-Le-Blanc** [comment]
July 24 - July 28, 2017:
- [x] send material to Lansing before call
- [x] Swiftly tasks
- [x] Lansing call
- [x] reply to Jonny - take out things from LA
- [x] check status of Topeka and Lansing in app
- [x] call Gogreenstreets initiative (figure out what they want, not advertise)
- [x] follow-up QLine (reassure him in saying that we aren't going to push the QLine live in the app until the integration with Passport and the link over to the QLine app is complete - push Swiftly if appropriate by asking if they're still having real time issues)
- [x] STM RFP
- [x] get RT accuracy data for MCTA + SEPTA from Juan

**Comment by Sophie-Le-Blanc** [comment]
July 31 - August 28, 2017:

- [x] give Lansing access to Beta 
- [x] Cleveland (see if can move to 4.2)
- [x] gogreenstreets
- [x] Louis: Rahul
- [x] add line 3 Torrance issue bug
Follow-ups:
    - [x] SMART (data)
    - [x] Topeka (data - trip planner)
    - [x] Topeka (bike share)
    - [x] Lansing (data)
    - [x] Canberra (agency)
    - [x] Jeff Parish (agency/consultant + ask data team to check file)

**Comment by Sophie-Le-Blanc** [comment]
August 7 - August 11, 2017:

- [x] STO MOU (english)
- [x] add column for ridership numbers to include students + add ballpark numbers for missing cities (north america)
- [x] check CARTA RT in Beta (don't see it on Friday)
- [x] HTA widgets
- [x] add Topeka customized information to app
- [x] fill in new GitHub w/ latest info
- [x] send Rabbit Transit material
- [x] Juan: updated graph for RT accuracy (with VTA, SEPTA bus, SPETA rail, RTD, MCTA) + MTAHC and TESTSEPTA feeds
- [x] Rabbit Transit call
- [x] launch mission bay
- [x] launch Lansing

**Comment by Sophie-Le-Blanc** [comment]
August 14 - August 18, 2017:
- [x] Juan: updated graph for RT accuracy (with VTA, SEPTA bus, SPETA rail, RTD, MCTA) + MTAHC and TESTSEPTA feeds
- [ ] launch Topeka
- [ ] finish emailing agencies improper guidelines + change for bikeshare
- [ ] find new agencies improper branding examples
- [ ] make changes to FAQ/agency kit
- [ ] get SMARTCA logo and vector

**Comment by Sophie-Le-Blanc** [comment]
-------------------------------------------------------------------------------------
- [ ] ask for SMART's GFTS through static link
- [ ] LA metro; we need to prove we can do better quality data than what they have
- [ ] Scoot
- [ ] discuss newsletter vs. twitter content w/ Joe
- [ ] move forward with LA + Vancouver w/ Swiftly when possible
- [ ] next update: check if Cleveland 77F re-route info is fixed
- [ ] get on HART about redesign?
- [ ] recueuil de news (kodo launching real time with transit app, gm of mbta)
